name: my_flutter
description: A new flutter module project.
version: 1.0.0+1

dependencies:
  package_info:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  flutter_webview_plugin: "^0.1.6"
  shared_preferences: "^0.4.1"
  event_bus: "^0.4.1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  module:
    androidPackage: com.example.myflutter
  assets:
      - images/ic_launcher_round.png
